name: build-and-release
on: [push]
jobs: 
  build-all: 
    runs-on: windows-2022
    defaults: 
      run: 
        shell: pwsh
        working-directory: C:\build
    steps: 
      - uses: jwlawson/actions-setup-cmake@v1.9
        with: 
          cmake-version: '3.22.x'
      - uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: 'C:\'
      - uses: actions/checkout@v2
        with: 
          path: project
          submodules: 'recursive'
      - run: New-Item C:\build -ItemType Directory
        working-directory: C:\
      - run: cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=C:\sniffer $env:GITHUB_WORKSPACE\project\code
      - run: cmake --build . --parallel
      - run: cmake --install .
      - run: New-Item C:\sniffer\doc -ItemType Directory
      - uses: docker://pandoc/core:2.18
        with:
          args: >-
             --pdf-engine=xelatex
             -V CJKmainfont="SimSun"
             -f markdown
             $env:GITHUB_WORKSPACE\project\report\report.md
             -o C:\sniffer\doc\report.pdf
      - run: cmake -E tar "cfv" C:\sniffer.zip --format=zip C:\sniffer
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: C:\sniffer.zip